
import Header from './components/Header'
import Nav from './components/Nav'
import SearchField from './components/SearchField'
import './globals.css'
import Providers from './Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <Header/>
        <Nav/>
        <SearchField/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
